name: Build Executables

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'  # This will trigger the workflow when pushing tags that start with 'v'
  pull_request:
    branches: [ main, master ]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-latest]  # Using ubuntu-22.04 for glibc compatibility
        python-version: ['3.13']

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for git describe
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    
    - name: Build with PyInstaller (Linux/macOS)
      if: matrix.os != 'windows-latest'
      run: |
        pyinstaller l7benchmark.spec
    
    - name: Build with PyInstaller (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        pyinstaller l7benchmark.spec
    
    - name: Rename executable for platform
      shell: bash
      run: |
        if [ "${{ matrix.os }}" == "ubuntu-22.04" ]; then
          platform="linux"
        elif [ "${{ matrix.os }}" == "macos-latest" ]; then
          platform="macos"
        elif [ "${{ matrix.os }}" == "windows-latest" ]; then
          platform="windows"
        fi
        
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          cp dist/l7benchmark.exe dist/l7benchmark-$platform.exe
        else
          cp dist/l7benchmark dist/l7benchmark-$platform
          chmod +x dist/l7benchmark-$platform
        fi
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: l7benchmark-${{ runner.os }}
        path: |
          dist/l7benchmark-*
    
    - name: Generate Release Notes
      if: github.ref_type == 'tag'
      id: generate_notes
      run: |
        echo "## L7Benchmark Release ${{ github.ref_name }}" > RELEASE_NOTES.md
        echo "" >> RELEASE_NOTES.md
        echo "### Changes in this version:" >> RELEASE_NOTES.md
        # Try to get the previous tag, or use the first commit if this is the first tag
        prev_tag=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || git rev-list --max-parents=0 HEAD)
        git log $prev_tag..HEAD --pretty=format:"- %s" >> RELEASE_NOTES.md

    - name: Create Release on Tag
      if: github.ref_type == 'tag'
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/l7benchmark-*
        body_path: RELEASE_NOTES.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
